In [1]:
pwd

'e:\\two_stage_model\\data_processing\\Speed_Processing'

In [2]:
cd ..

e:\two_stage_model\data_processing

In [3]:
import pandas as pd
import numpy as np
import pickle
from tqdm import tqdm

In [4]:
# Hyper-parameters during Data Processing 

country_name = 'Cranberry'
model_path = 'E:/two_stage_model'
slow_down_speed_upstream_range_mile = 0.3 # check if the range mile is in \processed_data\upstream_rage_dict

In [5]:
slow_down_speed_upstream_range_mile = float("{:.1f}".format(slow_down_speed_upstream_range_mile))

## Part 1. Read Files

In [5]:
# TMC Speed Data
spd_record_all = pickle.load(open(f"{model_path}/data/{country_name}/processed_data/{country_name}_df_spd_tmc_5min_all_from_1_min.pkl", "rb"))

In [6]:
spd_record_all

tmc_code,104+04435,104+04436,104+04437,104+04438,104+04439,104+04440,104+04441,104+04442,104+04443,104+04444,...,104P51588,104P51590,104P51594,104P51602,104P51608,104P51618,104P51620,104P51754,104P51833,104P51835
measurement_tstamp,,,,,,,,,,,,,,,,,,,,,
2022-02-01 05:30:00,58.0,45.00,56.85,63.00,52.0,57.0,64.0,67.0,70.0,71.0,...,32.00,57.20,36.00,45.20,41.15,40.00,30.77,39.23,44.0,40.78
2022-02-01 05:35:00,61.0,55.00,63.00,63.00,62.0,66.0,68.0,68.0,66.0,63.0,...,32.00,56.00,40.12,45.80,43.00,40.00,32.00,31.00,44.0,40.00
2022-02-01 05:40:00,64.0,63.00,55.00,56.00,60.0,67.0,70.0,66.0,59.0,56.0,...,33.58,57.00,43.00,48.95,44.75,40.00,32.00,43.00,44.0,41.75
2022-02-01 05:45:00,66.0,66.00,66.00,64.00,63.0,61.0,69.0,73.0,64.0,70.0,...,34.00,48.00,43.00,52.00,46.20,40.00,32.00,25.00,44.0,43.00
2022-02-01 05:50:00,63.0,61.00,62.00,63.00,64.0,71.0,73.0,73.0,71.0,60.0,...,18.89,53.53,43.00,43.54,42.00,40.00,18.00,42.18,44.0,42.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31 20:35:00,65.8,57.55,48.00,61.99,71.0,67.0,69.0,67.0,66.0,67.0,...,35.00,40.00,48.00,41.00,36.00,44.00,34.00,28.00,36.0,47.00
2024-01-31 20:40:00,63.0,57.00,57.40,62.00,66.0,68.0,69.0,70.0,68.0,66.0,...,35.00,40.00,48.00,41.00,36.00,44.00,34.00,25.00,36.0,47.00
2024-01-31 20:45:00,51.0,55.00,59.00,65.00,65.0,60.0,70.0,64.0,67.0,69.0,...,34.00,40.00,48.39,41.00,36.00,44.78,34.00,43.00,36.0,47.00
2024-01-31 20:50:00,63.0,73.00,79.00,80.00,63.0,60.0,60.0,71.0,73.0,62.0,...,34.00,40.00,67.00,41.00,36.00,46.00,48.00,36.58,49.0,47.00
2024-01-31 20:55:00,60.0,57.00,57.00,65.00,73.0,76.0,63.0,68.0,67.0,66.0,...,34.00,40.80,48.00,41.00,36.00,46.00,34.00,27.00,44.0,47.00

In [14]:
spd_record_all['104-04443']

measurement_tstamp
2022-02-01 05:30:00    72.0
2022-02-01 05:35:00    69.0
2022-02-01 05:40:00    66.0
2022-02-01 05:45:00    70.0
2022-02-01 05:50:00    68.0
                       ...
2024-01-31 20:35:00    68.0
2024-01-31 20:40:00    65.0
2024-01-31 20:45:00    63.0
2024-01-31 20:50:00    64.0
2024-01-31 20:55:00    63.0
Name: 104-04443, Length: 97092, dtype: float64

In [15]:
spd_record_all['104N04443']

measurement_tstamp
2022-02-01 05:30:00    71.0
2022-02-01 05:35:00    69.0
2022-02-01 05:40:00    67.0
2022-02-01 05:45:00    71.0
2022-02-01 05:50:00    71.0
                       ...
2024-01-31 20:35:00    73.0
2024-01-31 20:40:00    66.8
2024-01-31 20:45:00    63.0
2024-01-31 20:50:00    66.0
2024-01-31 20:55:00    64.0
Name: 104N04443, Length: 97092, dtype: float64

In [16]:
difference = spd_record_all['104-04443'] - spd_record_all['104N04443']

absolute_difference = difference.abs()

mean_absolute_difference = absolute_difference.mean()
print(mean_absolute_difference)

2.2811542660569355

In [7]:
speed_available_tmc_list = list(spd_record_all.columns)

## Part 2. Read Upstream Dict
-be careful to check if we have ran the dict for the specific length, other wise add value in Part 4 in \data_processing\geo_processing\generate_up_down_stream.ipynb

In [8]:
upstream_k_mile_dict =  pickle.load(open(f"{model_path}/data/{country_name}/processed_data/upstream_rage_dict/{country_name}_upstream_{slow_down_speed_upstream_range_mile}_mile.pkl", "rb"))

## Part 3. Generate Slowdown Speed

In [9]:
slowdown_speed_list = list(upstream_k_mile_dict.keys())
selected_link_spd = spd_record_all.loc[:, spd_record_all.columns.isin(slowdown_speed_list)]

In [10]:
df_slowdown_speed = pd.DataFrame(np.zeros(spd_record_all.shape), index=spd_record_all.index, columns=spd_record_all.columns)

In [11]:
no_upstream_selected_link_list = []
for tmc_id in tqdm(slowdown_speed_list):
    affected_link_list = upstream_k_mile_dict[tmc_id]
    if len(affected_link_list)==0:
        no_upstream_selected_link_list.append(tmc_id)
    affected_link_speed = spd_record_all.loc[:, spd_record_all.columns.isin(affected_link_list)]
    upstream_link_speed_average_list = list(affected_link_speed.mean(axis=1))
    analysis_link_speed_list = list(spd_record_all[tmc_id])
    slow_down_speed_list =  [upstream_link_speed_average - analysis_link_speed for upstream_link_speed_average, analysis_link_speed in zip(upstream_link_speed_average_list, analysis_link_speed_list)]
    df_slowdown_speed[tmc_id] = list(np.maximum(np.array(slow_down_speed_list), 0))

  0%|          | 0/1079 [00:00<?, ?it/s]

100%|██████████| 1079/1079 [00:35<00:00, 30.56it/s]

In [12]:
no_upstream_selected_link_list

['104+04435',
 '104+04555',
 '104+04685',
 '104+06181',
 '104+06269',
 '104+06347',
 '104+08080',
 '104+08640',
 '104+08648',
 '104+09108',
 '104+09352',
 '104+09360',
 '104+09593',
 '104+09594',
 '104+13464',
 '104+13470',
 '104+13681',
 '104+50582',
 '104-04492',
 '104-04493',
 '104-04544',
 '104-04807',
 '104-06374',
 '104-08648',
 '104-08958',
 '104-09099',
 '104-09127',
 '104-13705',
 '104-50441',
 '104N04493',
 '104P04516',
 '104P04550',
 '104P04554',
 '104P50660']

In [13]:
len(no_upstream_selected_link_list)

34

In [14]:
df_slowdown_speed

tmc_code,104+04435,104+04436,104+04437,104+04438,104+04439,104+04440,104+04441,104+04442,104+04443,104+04444,...,104P51588,104P51590,104P51594,104P51602,104P51608,104P51618,104P51620,104P51754,104P51833,104P51835
measurement_tstamp,,,,,,,,,,,,,,,,,,,,,
2022-02-01 05:30:00,NaN,7.50,0.0,0.0,10.8,6.0,0.000000,0.0,1.0,0.0,...,18.056667,0.000,0.0,0.0,0.0,0.0,24.23,6.30,0.680,0.0
2022-02-01 05:35:00,NaN,0.50,0.0,0.0,0.5,0.0,0.000000,2.0,1.0,0.5,...,15.463333,0.000,0.0,0.0,0.0,0.0,4.00,12.00,0.000,0.0
2022-02-01 05:40:00,NaN,1.00,0.0,0.0,0.0,0.0,0.000000,5.0,0.0,0.5,...,13.086667,0.000,0.0,0.0,0.0,0.0,1.00,0.00,0.000,0.0
2022-02-01 05:45:00,NaN,0.00,0.0,2.0,1.0,3.0,0.000000,0.0,1.0,0.0,...,10.333333,0.000,0.0,0.0,0.0,0.0,11.00,0.00,6.080,0.0
2022-02-01 05:50:00,NaN,0.50,0.0,0.0,0.0,0.0,0.000000,2.0,2.0,7.5,...,20.976667,0.000,0.0,0.0,0.0,0.0,30.00,4.82,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31 20:35:00,NaN,3.73,0.0,0.0,0.0,4.0,0.000000,2.0,0.0,0.0,...,10.666667,9.500,0.0,0.0,0.0,0.0,24.00,11.80,11.545,0.0
2024-01-31 20:40:00,NaN,3.50,0.0,0.0,0.0,0.0,0.130000,0.0,1.0,1.0,...,10.666667,9.500,0.0,0.0,0.0,0.0,24.00,12.20,10.500,0.0
2024-01-31 20:45:00,NaN,0.00,0.0,0.0,0.0,0.0,0.000000,5.0,0.0,2.0,...,11.666667,9.500,0.0,0.0,0.0,0.0,24.00,8.00,12.500,0.0
2024-01-31 20:50:00,NaN,0.00,0.0,6.0,17.5,0.0,1.333333,0.0,6.0,14.0,...,11.666667,9.500,0.0,0.0,0.0,0.0,0.00,9.22,0.000,0.0
2024-01-31 20:55:00,NaN,1.00,0.0,1.0,0.0,0.0,9.333333,3.0,2.0,3.5,...,6.683333,1.225,0.0,0.0,0.0,0.0,14.48,0.00,5.000,0.0

In [15]:
pickle.dump(df_slowdown_speed, open(f"{model_path}/data/{country_name}/processed_data/{country_name}_slowdown_speed.pkl", "wb"))

## Part 4. Generate Travel Time Index

In [16]:
df_all_tti_tmc_5min = spd_record_all.quantile(q=0.85, axis=0)/spd_record_all

In [17]:
df_all_tti_tmc_5min

tmc_code,104+04435,104+04436,104+04437,104+04438,104+04439,104+04440,104+04441,104+04442,104+04443,104+04444,...,104P51588,104P51590,104P51594,104P51602,104P51608,104P51618,104P51620,104P51754,104P51833,104P51835
measurement_tstamp,,,,,,,,,,,,,,,,,,,,,
2022-02-01 05:30:00,1.137931,1.355556,1.090589,1.000000,1.211538,1.157895,1.093750,1.059701,1.002571,0.943662,...,0.843750,0.919580,1.311111,1.128319,1.188019,1.200000,1.137472,0.996686,1.022727,1.088524
2022-02-01 05:35:00,1.081967,1.109091,0.984127,1.000000,1.016129,1.000000,1.029412,1.044118,1.063333,1.063492,...,0.843750,0.939286,1.176471,1.113537,1.136907,1.200000,1.093750,1.261290,1.022727,1.109750
2022-02-01 05:40:00,1.031250,0.968254,1.127273,1.125000,1.050000,0.985075,1.000000,1.075758,1.189492,1.196429,...,0.804050,0.922807,1.097674,1.041879,1.092447,1.200000,1.093750,0.909302,1.022727,1.063234
2022-02-01 05:45:00,1.000000,0.924242,0.939394,0.984375,1.000000,1.081967,1.014493,0.972603,1.096563,0.957143,...,0.794118,1.095833,1.097674,0.980769,1.058160,1.200000,1.093750,1.564000,1.022727,1.032326
2022-02-01 05:50:00,1.047619,1.000000,1.000000,1.000000,0.984375,0.929577,0.958904,0.972603,0.988451,1.116667,...,1.429328,0.982627,1.097674,1.171337,1.163976,1.200000,1.944444,0.926980,1.022727,1.042263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31 20:35:00,1.003040,1.059948,1.291667,1.016293,0.887324,0.985075,1.014493,1.059701,1.063333,1.000000,...,0.771429,1.315000,0.983333,1.243902,1.357972,1.090909,1.029412,1.396429,1.250000,0.944468
2024-01-31 20:40:00,1.047619,1.070175,1.080139,1.016129,0.954545,0.970588,1.014493,1.014286,1.032059,1.015152,...,0.771429,1.315000,0.983333,1.243902,1.357972,1.090909,1.029412,1.564000,1.250000,0.944468
2024-01-31 20:45:00,1.294118,1.109091,1.050847,0.969231,0.969231,1.100000,1.000000,1.109375,1.047463,0.971014,...,0.794118,1.315000,0.975408,1.243902,1.357972,1.071907,1.029412,0.909302,1.250000,0.944468
2024-01-31 20:50:00,1.047619,0.835616,0.784810,0.787500,1.000000,1.100000,1.166667,1.000000,0.961370,1.080645,...,0.794118,1.315000,0.704478,1.243902,1.357972,1.043478,0.729167,1.068890,0.918367,0.944468
2024-01-31 20:55:00,1.100000,1.070175,1.087719,0.969231,0.863014,0.868421,1.111111,1.044118,1.047463,1.015152,...,0.794118,1.289216,0.983333,1.243902,1.357972,1.043478,1.029412,1.448148,1.022727,0.944468

In [17]:
pickle.dump(df_all_tti_tmc_5min, open(f"{model_path}/data/{country_name}/processed_data/{country_name}_5min_tti.pkl", "wb"))