In [1]:
pwd

'e:\\two_stage_model\\data_processing\\Speed_Processing'

In [2]:
cd ..

e:\two_stage_model\data_processing

In [3]:
import pandas as pd
import numpy as np
import pickle
from tqdm import tqdm

In [4]:
# Hyper-parameters during Data Processing 

country_name = 'Cranberry'
model_path = 'E:/two_stage_model'

## Part 1. Read Files

In [7]:
# TMC Speed Data
spd_record_all = pickle.load(open(f"{model_path}/data/{country_name}/processed_data/{country_name}_df_spd_tmc_5min_all_from_1_min.pkl", "rb"))

In [5]:
mask = pickle.load(open(f"{model_path}/data/{country_name}/processed_data/{country_name}_raw_Waze.pkl", "rb"))

In [8]:
speed_available_tmc_list = list(spd_record_all.columns)

In [9]:
spd_links = list(spd_record_all.columns)

In [10]:
inc_links = list(mask.columns)

In [11]:
select_links = list(set(spd_links)&set(inc_links))

In [12]:
len(select_links)

1151

In [13]:
spd_record_all = spd_record_all[select_links]
mask  = mask[select_links]

In [14]:
spd_record_all['day_of_week'] = spd_record_all.index.dayofweek
spd_record_all['time_of_day'] = spd_record_all.index.time
mask['day_of_week'] = mask.index.dayofweek
mask['time_of_day'] = mask.index.time

In [15]:
mask

,104P06178,104P04643,104-09361,104P51590,104N04439,104+06357,104P04652,104+06619,104-50720,104P13500,...,104-13469,104+04445,104-06651,104N04552,104P04550,104P50426,104N04706,104+09249,day_of_week,time_of_day
2022-02-01 05:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,05:30:00
2022-02-01 05:35:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,05:35:00
2022-02-01 05:40:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,05:40:00
2022-02-01 05:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,05:45:00
2022-02-01 05:50:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,05:50:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31 20:35:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,20:35:00
2024-01-31 20:40:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,20:40:00
2024-01-31 20:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,20:45:00
2024-01-31 20:50:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,20:50:00
2024-01-31 20:55:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,20:55:00

In [16]:
def calculate_average_with_mask(df, mask_df, number):
    results = []
    
    # 根据mask_df将df中mask为1的值替换为NaN
    df_with_nan = df.mask(mask_df == 1)
    
    for i in tqdm(range(len(df))):
        current_row = df.iloc[i]
        day_of_week = current_row['day_of_week']
        time_of_day = current_row['time_of_day']
        
        # 获取当前行之前的同一星期几和时间段的行
        previous_rows = df_with_nan[(df['day_of_week'] == day_of_week) & 
                                    (df['time_of_day'] == time_of_day) & 
                                    (df.index < df.index[i])]
        
        # 获取当前行之后的同一星期几和时间段的行
        subsequent_rows = df_with_nan[(df['day_of_week'] == day_of_week) & 
                                      (df['time_of_day'] == time_of_day) & 
                                      (df.index > df.index[i])]
        
        # 选择前两行或后两行
        if len(previous_rows) >=  number:
            average_rows = previous_rows.tail( number)
        elif len(subsequent_rows) >=  number and len(previous_rows)< number:
            average_rows = subsequent_rows.head( number)
        else:
            raise ValueError('Wrong! ')
        
        # 如果依然不足两行数据，则结果为NaN
        #if average_rows.dropna(how='all').shape[0] ==0:
        #    avg_values = [np.nan] * len(df.columns[:-2])
        #else:
        avg_values = average_rows.iloc[:, :-2].mean(skipna=True).values
        
        results.append(avg_values)
    
    # 创建一个新的DataFrame来保存结果
    avg_df = pd.DataFrame(results, columns=df.columns[:-2], index=df.index)
    return avg_df

In [17]:
mask_avg =  calculate_average_with_mask(spd_record_all, mask, 3)

100%|██████████| 97092/97092 [16:23<00:00, 98.74it/s]

In [18]:
mask_avg

tmc_code,104P06178,104P04643,104-09361,104P51590,104N04439,104+06357,104P04652,104+06619,104-50720,104P13500,...,104N08593,104+13470,104-13469,104+04445,104-06651,104N04552,104P04550,104P50426,104N04706,104+09249
measurement_tstamp,,,,,,,,,,,,,,,,,,,,,
2022-02-01 05:30:00,67.000000,59.166667,22.713333,53.990000,64.666667,40.000000,63.183333,25.860000,13.0,29.370000,...,31.120000,40.000000,44.126667,68.333333,47.163333,61.653333,61.933333,24.000000,47.730000,29.563333
2022-02-01 05:35:00,62.000000,52.926667,23.926667,54.666667,63.000000,40.043333,54.666667,26.530000,13.0,29.333333,...,31.780000,40.196667,42.040000,71.333333,45.400000,60.793333,51.796667,24.000000,49.333333,29.576667
2022-02-01 05:40:00,59.456667,57.283333,22.573333,53.583333,68.000000,36.230000,55.333333,27.063333,13.0,28.000000,...,32.663333,36.796667,39.333333,74.000000,47.706667,52.000000,52.590000,23.666667,51.113333,29.253333
2022-02-01 05:45:00,65.333333,56.000000,19.596667,49.333333,69.333333,43.316667,57.743333,28.730000,13.0,27.730000,...,33.000000,32.000000,40.986667,67.000000,43.333333,59.666667,60.763333,23.666667,52.666667,30.106667
2022-02-01 05:50:00,58.333333,56.933333,23.983333,50.120000,68.666667,41.120000,48.666667,27.393333,13.0,27.666667,...,30.253333,36.766667,42.823333,73.333333,48.513333,58.666667,61.100000,23.670000,53.666667,33.310000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31 20:35:00,52.393333,50.333333,25.333333,45.333333,64.133333,39.463333,51.666667,24.463333,19.0,31.023333,...,28.666667,43.333333,39.530000,70.666667,37.996667,57.310000,54.266667,31.666667,51.056667,33.333333
2024-01-31 20:40:00,57.666667,48.666667,15.333333,45.066667,67.000000,37.863333,49.046667,24.333333,19.0,29.853333,...,30.333333,40.530000,36.333333,68.666667,37.463333,58.443333,49.666667,31.666667,53.050000,27.723333
2024-01-31 20:45:00,55.030000,45.000000,18.050000,47.860000,67.793333,40.333333,51.966667,24.796667,19.0,28.666667,...,26.000000,36.000000,40.463333,70.266667,37.196667,61.333333,54.393333,31.063333,49.790000,28.000000
2024-01-31 20:50:00,57.920000,56.000000,19.730000,48.000000,72.063333,37.656667,57.333333,24.666667,19.0,32.263333,...,26.000000,46.520000,36.000000,70.333333,42.333333,66.333333,52.666667,29.666667,47.933333,29.333333
2024-01-31 20:55:00,57.333333,47.876667,20.463333,48.000000,61.000000,38.000000,55.260000,24.666667,19.0,30.056667,...,26.000000,43.333333,43.733333,68.333333,41.936667,61.660000,48.666667,29.463333,50.666667,29.333333

In [21]:
total_nan = mask_avg.isna().sum().sum()

In [22]:
total_nan

55127

In [23]:
def fill_nan_with_nearest_date(df):
    # Ensure 'date' column exists in the DataFrame
    if 'date' not in df.columns:
        df['date'] = df.index.date
    
    # Group by 'date'
    grouped = df.groupby('date')

    # Apply forward fill and backward fill within each group
    filled_df = grouped.apply(lambda group: group.ffill().bfill())

    # Drop the 'date' column as it is no longer needed
    filled_df = filled_df.drop(columns=['date'])

    filled_df = filled_df.reset_index(level='date', drop=True)
    
    return filled_df

In [24]:
no_nan_mask_avg = fill_nan_with_nearest_date(mask_avg)

In [25]:
no_nan_mask_avg

tmc_code,104P06178,104P04643,104-09361,104P51590,104N04439,104+06357,104P04652,104+06619,104-50720,104P13500,...,104N08593,104+13470,104-13469,104+04445,104-06651,104N04552,104P04550,104P50426,104N04706,104+09249
measurement_tstamp,,,,,,,,,,,,,,,,,,,,,
2022-02-01 05:30:00,67.000000,59.166667,22.713333,53.990000,64.666667,40.000000,63.183333,25.860000,13.0,29.370000,...,31.120000,40.000000,44.126667,68.333333,47.163333,61.653333,61.933333,24.000000,47.730000,29.563333
2022-02-01 05:35:00,62.000000,52.926667,23.926667,54.666667,63.000000,40.043333,54.666667,26.530000,13.0,29.333333,...,31.780000,40.196667,42.040000,71.333333,45.400000,60.793333,51.796667,24.000000,49.333333,29.576667
2022-02-01 05:40:00,59.456667,57.283333,22.573333,53.583333,68.000000,36.230000,55.333333,27.063333,13.0,28.000000,...,32.663333,36.796667,39.333333,74.000000,47.706667,52.000000,52.590000,23.666667,51.113333,29.253333
2022-02-01 05:45:00,65.333333,56.000000,19.596667,49.333333,69.333333,43.316667,57.743333,28.730000,13.0,27.730000,...,33.000000,32.000000,40.986667,67.000000,43.333333,59.666667,60.763333,23.666667,52.666667,30.106667
2022-02-01 05:50:00,58.333333,56.933333,23.983333,50.120000,68.666667,41.120000,48.666667,27.393333,13.0,27.666667,...,30.253333,36.766667,42.823333,73.333333,48.513333,58.666667,61.100000,23.670000,53.666667,33.310000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31 20:35:00,52.393333,50.333333,25.333333,45.333333,64.133333,39.463333,51.666667,24.463333,19.0,31.023333,...,28.666667,43.333333,39.530000,70.666667,37.996667,57.310000,54.266667,31.666667,51.056667,33.333333
2024-01-31 20:40:00,57.666667,48.666667,15.333333,45.066667,67.000000,37.863333,49.046667,24.333333,19.0,29.853333,...,30.333333,40.530000,36.333333,68.666667,37.463333,58.443333,49.666667,31.666667,53.050000,27.723333
2024-01-31 20:45:00,55.030000,45.000000,18.050000,47.860000,67.793333,40.333333,51.966667,24.796667,19.0,28.666667,...,26.000000,36.000000,40.463333,70.266667,37.196667,61.333333,54.393333,31.063333,49.790000,28.000000
2024-01-31 20:50:00,57.920000,56.000000,19.730000,48.000000,72.063333,37.656667,57.333333,24.666667,19.0,32.263333,...,26.000000,46.520000,36.000000,70.333333,42.333333,66.333333,52.666667,29.666667,47.933333,29.333333
2024-01-31 20:55:00,57.333333,47.876667,20.463333,48.000000,61.000000,38.000000,55.260000,24.666667,19.0,30.056667,...,26.000000,43.333333,43.733333,68.333333,41.936667,61.660000,48.666667,29.463333,50.666667,29.333333

In [29]:
total_nan = no_nan_mask_avg.isna().sum().sum()

In [30]:
total_nan

372

In [33]:
no_nan_mask_avg =  no_nan_mask_avg.fillna(0)

In [34]:
total_nan = no_nan_mask_avg.isna().sum().sum()

In [35]:
total_nan

0

In [36]:
pickle.dump(mask_avg, open(f"{model_path}/data/{country_name}/processed_data/{country_name}_recurrent_ha_nan.pkl", "wb"))

In [37]:
pickle.dump(no_nan_mask_avg, open(f"{model_path}/data/{country_name}/processed_data/{country_name}_recurrent_ha_no_nan.pkl", "wb"))